name: flutter_spaces
description: Marketing webpage for weekly Flutter Spaces
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  static_shock: ^0.0.14

  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
